stages:
  - build
  - check
  - deploy

build:
  stage: build
  image: registry.firestick.games/sean/thirty-ci-images/$DISTRO-$ARCH:latest
  variables:
    CC: $CC
  tags:
    - $ARCH
  script:
    - meson setup build
    - ninja -C build
  parallel:
    matrix:
      - CC: [ gcc, clang ]
        DISTRO: [ debian, alpine, tumbleweed ]
        ARCH: [ x86_64, aarch64 ]

scan-build:
  stage: check
  image: registry.firestick.games/sean/thirty-ci-images/$DISTRO-$ARCH:latest
  variables:
    CC: clang
  tags:
    - $ARCH
  script:
    - meson setup build
    - ninja -C build scan-build
  parallel:
    matrix:
      - DISTRO: [ debian, alpine, tumbleweed ]
        ARCH: [ x86_64, aarch64 ]
  artifacts:
    paths:
      - build/meson-logs/scanbuild/*

## Docker image

.kaniko: &kaniko
  stage: deploy
  parallel:
    matrix:
      - ARCH: [ x86_64, aarch64 ]
  tags:
    - $ARCH
  image:
    name: gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [""]
  before_script:
    - if [[ "$ARCH" != "x86_64" ]]; then
        export SUFFIX="-$ARCH";
      fi
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

docker:
  <<: *kaniko
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "Dockerfile" --build-arg ARCH=$ARCH
      --destination "${CI_REGISTRY_IMAGE}:dev${SUFFIX}"
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

docker tagged:
  <<: *kaniko
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "Dockerfile" --build-arg ARCH=$ARCH
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}${SUFFIX}"
      --destination "${CI_REGISTRY_IMAGE}:latest${SUFFIX}"
  rules:
     - if: $CI_COMMIT_TAG
