stages:
  - build

build:
  stage: build
  image: debian:latest
  before_script:
    - export DEBIAN_FRONTEND=noninteractive && export TZ=Etc/UTC && apt-get update && apt-get -y dist-upgrade && apt-get -y install build-essential meson ninja-build zlib1g-dev
  script:
    - meson setup build
    - cd build && ninja

build alpine:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --update alpine-sdk zlib ninja-build
  script:
    - meson setup build
    - cd build && ninja
